### ISSUE TITLE
Wrong JUnit reporting makes failed test to be treaded as passing

### ISSUE THREAD

**Issue by jotel** [helmethair-co/scalatest-junit-runner#22]
**Describe the bug**
When test suite fail in lifecycle methods e.g. before/after these failures are ignored and not reported properly back to JUnit which makes a dangerous situation when failed tests are actually treated as passing

**To Reproduce**
1. clone https://github.com/jotel/aborted-tetsts-example
2. run `./gradlew check`
3. Build is successful, but it should not be

**Expected behavior**

The build should fail and all suites should be present in build/test-results/test/

**Screenshots**
There are four suites and five tests in the sample build but only two of both of them are reported.

<img width="1151" alt="Screenshot 2020-06-03 at 10 50 44" src="https://user-images.githubusercontent.com/492425/83622827-682aeb80-a588-11ea-888d-c8bb283342a4.png">

**Additional context**
Also ignored test in FunSuite marked `ignore(...)` are not properly reported as disabled.

**Comment by giurim** [comment]
At first, it seems to me, that runner reports an "aborted" test to JUnit, but that somehow does not make the suite fail.

**Comment by jotel** [comment]
I'm suspecting  `rootTestDescriptor` in here:
https://github.com/helmethair-co/scalatest-junit-runner/blob/master/src/main/java/co/helmethair/scalatest/reporter/JUnitReporter.java#L56
 
this might give some clues:
https://github.com/scalatest/scalatest/blob/00b4f4a31602d08db5d8f1d9eafbdeccf3c72f02/scalatest/src/main/scala/org/scalatest/tools/JUnitXmlReporter.scala

**Comment by giurim** [comment]
I also think that is the reason. Thank you!

**Comment by jotel** [comment]
Hi @giurim, thanks for the fix... is the release with the change going to be published soon?

**Comment by giurim** [comment]
The central repository manager was prettyslow yesterday and it still gives weird errors. I try to figure out and push the release asap.

**Comment by giurim** [comment]
I will setup a JCenter account and try to release there

**Comment by giurim** [comment]
Hi @jotel,

Thank you for the patience. You can access 0.1.5 on jcenter/bintray. I was still not able to figure out what happened to maven central but it should eventually sync there as well.

**Comment by giurim** [comment]
Hi @jotel, it is synced to maven central
