### ISSUE TITLE
Add support for other discovery selectors

### ISSUE THREAD

**Issue by giurim** [helmethair-co/scalatest-junit-runner#8]
Currently only class discovery selector is supported. Add support for at least
- path selector
- modules selector

**Comment by slandelle** [comment]
Hi there,

If I get this issue right, this plugin currently only supports discovering test classes whose name ends with "Test" and doesn't discover classes with different naming pattern but with classes or methods annotated `@Test`. Am I correct?

**Comment by giurim** [comment]
Hi, at least for Gradle it is not the case. This issue is about other
(afaik rarely used) features of Junit 5.

The test runner and the Junit 5 environment works together. The environment
"offers" things to discover (classes, files, etc) and the runner discovers
the tests. In the case of class discovery Gradle enumerates all classes on
the test classpath and the runner basically select all the classes which is
assignable from the Scalatest Suite class (at least the last version does
this).

So as far as we know all Scalatest test should be discovered if this is not
the case pls file a bug and I will look into it.

**Comment by slandelle** [comment]
@giurim Sorry, I realized my own mistake and deleted my comment but I guess you had already received a notification. Actually, only collecting classes whose name contains "Test" is maven-surefire-plugin's convention. I can't say I like it though...
Sorry for the noise and thanks for this project!

**Comment by giurim** [comment]
@slandelle Hi, no worries, yes I was OOO and replied to the notification email directly on my phone. The maven-surefire-plugin convention is an interesting problem, will look into that, maybe something can be done.

**Comment by slandelle** [comment]
I suspect the maven-surefire-plugin convention is something from the past, before annotations landed in Java 5 and they don't want a breaking change.

**Comment by giurim** [comment]
Hi, you are right. The default inclusion pattern for the Maven Surefire plugin makes it only "discover" classes (files) matching the following patterns:

- `**/Test*.java`
- `**/*Test.java`
- `**/*Tests.java`
- `**/*TestCase.java`

See inclusion/exclusion configuration details: [Inclusions and Exclusions of Tests](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html)

I tried the following Surefire configuration (which is pretty permissive) and I was able to run Scalatest tests with any name.
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${maven.surefire.version}</version>
    <configuration>
        <includes>
            <include>*</include>
        </includes>
        <excludes>
            <exclude/>
        </excludes>
    </configuration>
</plugin>
```

**Comment by giurim** [comment]
I did not really find use for supporting other discovery selectors. I also checked several Junit Engine implementations and I think it is enough to support class-based discovery.
